# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 17:19
from __future__ import unicode_literals

from django.db import migrations
import csv


def import_rater_data(apps, schema_editor):
    Rater = apps.get_model("movie_app", "Rater")
    with open("data/u.user") as infile:
        rater = csv.reader(infile, delimiter="|")
        for row in rater:
            Rater.objects.create(id=row[0], age=row[1], gender=row[2], occupation=row[3], zip_code=row[4])
    # raise Exception("1 yay")


def import_movie_data(apps, schema_editor):
    Movie = apps.get_model("movie_app", "Movie")
    with open("data/u.item", encoding='latin1') as infile:
        movie = csv.reader(infile, delimiter="|")
        for row in movie:
            Movie.objects.create(id=row[0], movie_title=row[1], release_date=row[2], video_release_date=row[3],
                                 imdb_url=row[4], unknown=row[5], action=row[6], adventure=row[7], animation=row[8],
                                 childrens=row[9], comedy=row[10], crime=row[11], documentry=row[12], drama=row[13],
                                 fantasy=row[14], film_noir=row[15], horror=row[16], musical=row[17], mystery=row[18],
                                 romance=row[19], sci_fi=row[20], thriller=row[21], war=row[22], western=row[23])
    # raise Exception("2 yay")


def import_rating_data(apps, schema_editor):
    Rating = apps.get_model("movie_app", "Rating")
    Movie = apps.get_model("movie_app", "Movie")
    Rater = apps.get_model("movie_app", "Rater")
    with open("data/u.data") as infile:
        rating = csv.reader(infile, delimiter="\t")
        for row in rating:
            movie_movie_id = Movie.objects.get(id=row[1])
            rater_user_id = Rater.objects.get(id=row[0])
            Rating.objects.create(user_id=rater_user_id, item_id=movie_movie_id, rating=row[2], timestamp=row[3])
    # raise Exception("3 yay")      # This is a great test


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_rater_data),
        migrations.RunPython(import_movie_data),
        migrations.RunPython(import_rating_data),
    ]
